In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
c=np.array([(1,2,3),(4,5,6)])

In [6]:
print(c)

[[1 2 3]
 [4 5 6]]


In [7]:
trans=np.transpose(c)

In [8]:
print(trans)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
trans.ravel()

array([1, 4, 2, 5, 3, 6])

In [10]:
c.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
ze=np.zeros((3,3))

In [12]:
print(ze)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
one=np.ones((3,3))

In [14]:
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
